# Generated by Django 4.1.3 on 2023-07-03 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('about1', models.CharField(max_length=100)),
                ('company1', models.CharField(max_length=100)),
                ('job1', models.CharField(max_length=50)),
                ('country1', models.CharField(max_length=20)),
                ('adress1', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=20)),
                ('twitter1', models.CharField(blank=True, max_length=30)),
                ('facebook1', models.CharField(blank=True, max_length=30)),
                ('instagram1', models.CharField(blank=True, max_length=30)),
                ('linkdin1', models.CharField(blank=True, max_length=30)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
