# Generated by Django 4.1.3 on 2023-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile1',
            name='image1',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
