# Generated by Django 4.1.3 on 2023-07-04 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_user_profile1_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=100)),
                ('image2', models.ImageField(blank=True, upload_to='profile')),
                ('about2', models.CharField(blank=True, max_length=300)),
                ('company2', models.CharField(blank=True, max_length=100)),
                ('job2', models.CharField(blank=True, max_length=50)),
                ('country2', models.CharField(blank=True, max_length=20)),
                ('adress2', models.CharField(blank=True, max_length=200)),
                ('phone2', models.CharField(blank=True, max_length=30)),
                ('email2', models.CharField(blank=True, max_length=30)),
                ('twitter2', models.CharField(blank=True, max_length=30)),
                ('facebook2', models.CharField(blank=True, max_length=30)),
                ('instagram2', models.CharField(blank=True, max_length=30)),
                ('linkdin2', models.CharField(blank=True, max_length=30)),
                ('user2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
