# Generated by Django 4.1.3 on 2023-07-06 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_user_profile2'),
    ]

    operations = [
        migrations.CreateModel(
            name='task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title1', models.CharField(max_length=50)),
                ('task_desc1', models.CharField(max_length=150)),
                ('task_priority1', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('task_status1', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished')], max_length=20)),
                ('task_due1', models.DateField()),
                ('task_created_date', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
