# Generated by Django 4.1.3 on 2023-07-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_faq_alter_task1_task_priority1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('feed_desc', models.CharField(max_length=350)),
                ('country', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
