# Generated by Django 4.1.3 on 2023-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile2',
            name='notif_acc',
            field=models.BooleanField(default=False, verbose_name='notif'),
        ),
    ]
