# Generated by Django 4.1.3 on 2023-07-13 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_news_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1',
            name='task_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task1',
            name='task_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
