# Generated by Django 4.1.3 on 2023-07-13 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_announce'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name3', models.CharField(max_length=100)),
                ('image3', models.ImageField(blank=True, upload_to='userprofile')),
                ('about3', models.CharField(blank=True, max_length=400)),
                ('company3', models.CharField(blank=True, max_length=100)),
                ('job3', models.CharField(blank=True, max_length=50)),
                ('country3', models.CharField(blank=True, max_length=20)),
                ('adress3', models.CharField(blank=True, max_length=300)),
                ('phone3', models.CharField(blank=True, max_length=30)),
                ('email3', models.CharField(blank=True, max_length=30)),
                ('twitter3', models.CharField(blank=True, max_length=30)),
                ('facebook3', models.CharField(blank=True, max_length=30)),
                ('instagram3', models.CharField(blank=True, max_length=30)),
                ('linkdin3', models.CharField(blank=True, max_length=30)),
                ('notif_acc3', models.BooleanField(default=False, verbose_name='notif')),
                ('user3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
