# Generated by Django 4.1.3 on 2023-07-21 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_updates',
            name='news_catagory',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
