# Generated by Django 4.1.3 on 2023-07-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_task1_task_activation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile2',
            name='user2',
        ),
        migrations.DeleteModel(
            name='user_profile1',
        ),
        migrations.DeleteModel(
            name='user_profile2',
        ),
    ]
