# Generated by Django 4.1.3 on 2023-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_user_profile2_user2_delete_user_profile1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_updates',
            name='news_catagory',
            field=models.CharField(choices=[('General', 'General'), ('Featured', 'Featured')], max_length=100),
        ),
    ]
