# Generated by Django 4.1.3 on 2023-08-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_news_updates_news_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='ann_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
