# Generated by Django 4.2.4 on 2023-08-04 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0019_task1_task_attach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('project_type', models.CharField(choices=[('Type1', 'Type1'), ('Type2', 'Type2'), ('Type3', 'Type3')], max_length=100)),
                ('project_desc', models.CharField(max_length=300)),
                ('project_start', models.DateField()),
                ('project_end', models.DateField()),
                ('duration', models.CharField(max_length=30)),
                ('hours', models.IntegerField()),
                ('project_status', models.CharField(choices=[('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Complete,', 'Complete,'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
