# Generated by Django 4.2.4 on 2023-08-04 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0021_projectlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=100)),
                ('issue_desc', models.CharField(max_length=500)),
                ('issue_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved,', 'Resolved,')], max_length=50)),
                ('issue_priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('issue_attach', models.FileField(blank=True, upload_to='issueattach')),
                ('Projectlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectlist')),
                ('issue_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
