# Generated by Django 4.2.4 on 2023-08-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='Projectlist',
            new_name='projectlist',
        ),
    ]
