# Generated by Django 4.2.4 on 2023-08-07 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_projectlist_issue_projectlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
