# Generated by Django 4.2.4 on 2023-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_project_project_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
