# Generated by Django 4.2.4 on 2023-08-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_project_project_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_activation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
