# Generated by Django 4.2.4 on 2023-08-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_projectlist_list_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='list_activation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
