# Generated by Django 4.2.4 on 2023-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_projectlist_list_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_activation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
