# Generated by Django 4.2.4 on 2023-08-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_issue_issue_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_issues', models.FileField(blank=True, null=True, upload_to='attachements')),
            ],
        ),
    ]
