# Generated by Django 4.2.4 on 2023-08-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_attachements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_attach',
        ),
    ]
