# Generated by Django 4.2.4 on 2023-08-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_issue_issue_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_attach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.attachements'),
        ),
    ]
