# Generated by Django 4.2.4 on 2023-08-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_issue_issue_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachements',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.issue'),
        ),
    ]
