# Generated by Django 4.2.4 on 2023-08-09 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_attachements_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachements',
            name='attach_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
