# Generated by Django 4.2.4 on 2023-08-10 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_taskattach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_title', models.CharField(max_length=100)),
                ('subtask_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Finished', 'Finished')], max_length=50)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task1')),
            ],
        ),
    ]
