# Generated by Django 4.2.4 on 2023-08-16 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0046_remove_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='assignee',
            field=models.ManyToManyField(through='myapp.ProjectAssignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
