# Generated by Django 4.2.4 on 2023-08-16 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0047_projectassignee_project_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assignee',
            field=models.ManyToManyField(blank=True, null=True, through='myapp.ProjectAssignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
